name: continuous-integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Set up Adopt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Add git safe.directory for container
        run: |
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
      - name: Build project
        run: |
          ./gradlew assemble
      - name: Test project
        run: |
          ./gradlew test
      - name: Send code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
